// <auto-generated />
using System;
using JcmSoft.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JcmSoft.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827185225_AddConfigurations")]
    partial class AddConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JcmSoft.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Email = "contato@gulossw.com",
                            Nome = "Gulos Softwares",
                            Telefone = "1130121001"
                        },
                        new
                        {
                            ClienteId = 2,
                            Email = "contato@technova.com",
                            Nome = "TechNova Solutions",
                            Telefone = "1130121002"
                        },
                        new
                        {
                            ClienteId = 3,
                            Email = "contato@bompreco.com",
                            Nome = "Mercado Bom Preco",
                            Telefone = "1130121003"
                        },
                        new
                        {
                            ClienteId = 4,
                            Email = "contato@hospitalvida.com",
                            Nome = "Hospital Vida",
                            Telefone = "1130121004"
                        },
                        new
                        {
                            ClienteId = 5,
                            Email = "contato@transrapida.com",
                            Nome = "Transportadora Rapida",
                            Telefone = "1130121005"
                        },
                        new
                        {
                            ClienteId = 6,
                            Email = "contato@escolafuturo.com",
                            Nome = "Escola Futuro",
                            Telefone = "1130121006"
                        },
                        new
                        {
                            ClienteId = 7,
                            Email = "contato@restaurantesabor.com",
                            Nome = "Restaurante Sabor",
                            Telefone = "1130121007"
                        },
                        new
                        {
                            ClienteId = 8,
                            Email = "contato@horizonte.com",
                            Nome = "Construtora Horizonte",
                            Telefone = "1130121008"
                        },
                        new
                        {
                            ClienteId = 9,
                            Email = "contato@movimento.com",
                            Nome = "Academia Movimento",
                            Telefone = "1130121009"
                        },
                        new
                        {
                            ClienteId = 10,
                            Email = "contato@bancopaulista.com",
                            Nome = "Banco Paulista",
                            Telefone = "1130121010"
                        },
                        new
                        {
                            ClienteId = 11,
                            Email = "contato@clinicacentral.com",
                            Nome = "Clinica Central",
                            Telefone = "1130121011"
                        },
                        new
                        {
                            ClienteId = 12,
                            Email = "contato@livrariacultura.com",
                            Nome = "Livraria Cultura",
                            Telefone = "1130121012"
                        },
                        new
                        {
                            ClienteId = 13,
                            Email = "contato@petfeliz.com",
                            Nome = "Pet Feliz",
                            Telefone = "1130121013"
                        },
                        new
                        {
                            ClienteId = 14,
                            Email = "contato@autocenter.com",
                            Nome = "Auto Center Brasil",
                            Telefone = "1130121014"
                        },
                        new
                        {
                            ClienteId = 15,
                            Email = "contato@hotelcentral.com",
                            Nome = "Hotel Central",
                            Telefone = "1130121015"
                        },
                        new
                        {
                            ClienteId = 16,
                            Email = "contato@farmaciasaude.com",
                            Nome = "Farmacia Saude",
                            Telefone = "1130121016"
                        },
                        new
                        {
                            ClienteId = 17,
                            Email = "contato@comercialandrade.com",
                            Nome = "Comercial Andrade",
                            Telefone = "1130121017"
                        },
                        new
                        {
                            ClienteId = 18,
                            Email = "contato@grupoalpha.com",
                            Nome = "Grupo Educacional Alpha",
                            Telefone = "1130121018"
                        },
                        new
                        {
                            ClienteId = 19,
                            Email = "contato@metalforte.com",
                            Nome = "Industria Metal Forte",
                            Telefone = "1130121019"
                        },
                        new
                        {
                            ClienteId = 20,
                            Email = "contato@logisticaexpress.com",
                            Nome = "Logistica Express",
                            Telefone = "1130121020"
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Descricao = "Desenvolvimento de sistemas e aplicações",
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Descricao = "Pesquisa, análise e inovação de produtos",
                            Nome = "Pesquisa"
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Descricao = "Gestão financeira e contábil da empresa",
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            FuncionarioId = 1,
                            Cargo = "Desenvolvedor C#",
                            DataContratacao = new DateOnly(2024, 1, 10),
                            DepartamentoId = 1,
                            Nome = "Luiz Almeida",
                            Salario = 4500.00m
                        },
                        new
                        {
                            FuncionarioId = 2,
                            Cargo = "Desenvolvedora Front-end",
                            DataContratacao = new DateOnly(2024, 2, 15),
                            DepartamentoId = 1,
                            Nome = "Mariana Souza",
                            Salario = 4200.00m
                        },
                        new
                        {
                            FuncionarioId = 3,
                            Cargo = "Desenvolvedor Back-end",
                            DataContratacao = new DateOnly(2024, 3, 20),
                            DepartamentoId = 1,
                            Nome = "Carlos Oliveira",
                            Salario = 4800.00m
                        },
                        new
                        {
                            FuncionarioId = 4,
                            Cargo = "Analista de Sistemas",
                            DataContratacao = new DateOnly(2024, 4, 5),
                            DepartamentoId = 1,
                            Nome = "Ana Beatriz Santos",
                            Salario = 5000.00m
                        },
                        new
                        {
                            FuncionarioId = 5,
                            Cargo = "Desenvolvedor Full Stack",
                            DataContratacao = new DateOnly(2024, 5, 12),
                            DepartamentoId = 1,
                            Nome = "Rafael Costa",
                            Salario = 5500.00m
                        },
                        new
                        {
                            FuncionarioId = 6,
                            Cargo = "Pesquisadora",
                            DataContratacao = new DateOnly(2024, 6, 3),
                            DepartamentoId = 2,
                            Nome = "Juliana Martins",
                            Salario = 3800.00m
                        },
                        new
                        {
                            FuncionarioId = 7,
                            Cargo = "Analista de Pesquisa",
                            DataContratacao = new DateOnly(2024, 6, 18),
                            DepartamentoId = 2,
                            Nome = "Pedro Henrique Lima",
                            Salario = 4000.00m
                        },
                        new
                        {
                            FuncionarioId = 8,
                            Cargo = "UX Researcher",
                            DataContratacao = new DateOnly(2024, 7, 1),
                            DepartamentoId = 2,
                            Nome = "Camila Ferreira",
                            Salario = 4300.00m
                        },
                        new
                        {
                            FuncionarioId = 9,
                            Cargo = "Cientista de Dados",
                            DataContratacao = new DateOnly(2024, 7, 15),
                            DepartamentoId = 2,
                            Nome = "Gabriel Rocha",
                            Salario = 5200.00m
                        },
                        new
                        {
                            FuncionarioId = 10,
                            Cargo = "Analista de Produtos",
                            DataContratacao = new DateOnly(2024, 8, 22),
                            DepartamentoId = 2,
                            Nome = "Beatriz Mendes",
                            Salario = 4700.00m
                        },
                        new
                        {
                            FuncionarioId = 11,
                            Cargo = "Analista Financeiro",
                            DataContratacao = new DateOnly(2024, 9, 10),
                            DepartamentoId = 3,
                            Nome = "Ricardo Gomes",
                            Salario = 4200.00m
                        },
                        new
                        {
                            FuncionarioId = 12,
                            Cargo = "Contadora",
                            DataContratacao = new DateOnly(2024, 9, 20),
                            DepartamentoId = 3,
                            Nome = "Fernanda Alves",
                            Salario = 5000.00m
                        },
                        new
                        {
                            FuncionarioId = 13,
                            Cargo = "Assistente Financeiro",
                            DataContratacao = new DateOnly(2024, 10, 1),
                            DepartamentoId = 3,
                            Nome = "Thiago Nunes",
                            Salario = 3000.00m
                        },
                        new
                        {
                            FuncionarioId = 14,
                            Cargo = "Analista de Custos",
                            DataContratacao = new DateOnly(2024, 10, 15),
                            DepartamentoId = 3,
                            Nome = "Patricia Ramos",
                            Salario = 4500.00m
                        },
                        new
                        {
                            FuncionarioId = 15,
                            Cargo = "Gerente Financeiro",
                            DataContratacao = new DateOnly(2024, 11, 1),
                            DepartamentoId = 3,
                            Nome = "Eduardo Castro",
                            Salario = 6500.00m
                        },
                        new
                        {
                            FuncionarioId = 16,
                            Cargo = "Desenvolvedor C#",
                            DataContratacao = new DateOnly(2026, 3, 10),
                            DepartamentoId = 1,
                            Nome = "Lucas Barbosa",
                            Salario = 4400.00m
                        },
                        new
                        {
                            FuncionarioId = 17,
                            Cargo = "Desenvolvedora Mobile",
                            DataContratacao = new DateOnly(2026, 6, 15),
                            DepartamentoId = 1,
                            Nome = "Isabela Dias",
                            Salario = 4600.00m
                        },
                        new
                        {
                            FuncionarioId = 18,
                            Cargo = "Analista de Dados",
                            DataContratacao = new DateOnly(2026, 3, 1),
                            DepartamentoId = 2,
                            Nome = "Bruno Cardoso",
                            Salario = 4900.00m
                        },
                        new
                        {
                            FuncionarioId = 19,
                            Cargo = "Pesquisadora de Mercado",
                            DataContratacao = new DateOnly(2026, 7, 15),
                            DepartamentoId = 2,
                            Nome = "Larissa Teixeira",
                            Salario = 4100.00m
                        },
                        new
                        {
                            FuncionarioId = 20,
                            Cargo = "Analista Financeiro",
                            DataContratacao = new DateOnly(2026, 8, 1),
                            DepartamentoId = 3,
                            Nome = "Gustavo Freitas",
                            Salario = 4300.00m
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.Property<int>("FuncionarioDetalheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioDetalheId"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoResidencial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FuncionarioDetalheId");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.ToTable("FuncionarioDetalhes");

                    b.HasData(
                        new
                        {
                            FuncionarioDetalheId = 1,
                            CPF = "50231231231",
                            Celular = "11987654321",
                            DataNascimento = new DateTime(1998, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua das Flores, 120",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "luiz.jpg",
                            FuncionarioId = 1,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 2,
                            CPF = "50231231232",
                            Celular = "11987654322",
                            DataNascimento = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Augusta, 450",
                            Escolaridade = 3,
                            EstadoCivil = 1,
                            Foto = "mariana.jpg",
                            FuncionarioId = 2,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 3,
                            CPF = "50231231233",
                            Celular = "11987654323",
                            DataNascimento = new DateTime(1995, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Vergueiro, 890",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "carlos.jpg",
                            FuncionarioId = 3,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 4,
                            CPF = "50231231234",
                            Celular = "11987654324",
                            DataNascimento = new DateTime(1996, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Av. Paulista, 1500",
                            Escolaridade = 4,
                            EstadoCivil = 1,
                            Foto = "ana.jpg",
                            FuncionarioId = 4,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 5,
                            CPF = "50231231235",
                            Celular = "11987654325",
                            DataNascimento = new DateTime(1994, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Tatuape, 300",
                            Escolaridade = 4,
                            EstadoCivil = 0,
                            Foto = "rafael.jpg",
                            FuncionarioId = 5,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 6,
                            CPF = "50231231236",
                            Celular = "11987654326",
                            DataNascimento = new DateTime(1999, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Mooca, 220",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "juliana.jpg",
                            FuncionarioId = 6,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 7,
                            CPF = "50231231237",
                            Celular = "11987654327",
                            DataNascimento = new DateTime(1997, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Santana, 720",
                            Escolaridade = 3,
                            EstadoCivil = 1,
                            Foto = "pedro.jpg",
                            FuncionarioId = 7,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 8,
                            CPF = "50231231238",
                            Celular = "11987654328",
                            DataNascimento = new DateTime(1996, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Vila Mariana, 180",
                            Escolaridade = 4,
                            EstadoCivil = 0,
                            Foto = "camila.jpg",
                            FuncionarioId = 8,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 9,
                            CPF = "50231231239",
                            Celular = "11987654329",
                            DataNascimento = new DateTime(1993, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Ipiranga, 550",
                            Escolaridade = 4,
                            EstadoCivil = 1,
                            Foto = "gabriel.jpg",
                            FuncionarioId = 9,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 10,
                            CPF = "50231231240",
                            Celular = "11987654330",
                            DataNascimento = new DateTime(1998, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Consolacao, 900",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "beatriz.jpg",
                            FuncionarioId = 10,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 11,
                            CPF = "50231231241",
                            Celular = "11987654331",
                            DataNascimento = new DateTime(1992, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Liberdade, 100",
                            Escolaridade = 3,
                            EstadoCivil = 1,
                            Foto = "ricardo.jpg",
                            FuncionarioId = 11,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 12,
                            CPF = "50231231242",
                            Celular = "11987654332",
                            DataNascimento = new DateTime(1990, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Bela Vista, 340",
                            Escolaridade = 4,
                            EstadoCivil = 1,
                            Foto = "fernanda.jpg",
                            FuncionarioId = 12,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 13,
                            CPF = "50231231243",
                            Celular = "11987654333",
                            DataNascimento = new DateTime(2000, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Penha, 410",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "thiago.jpg",
                            FuncionarioId = 13,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 14,
                            CPF = "50231231244",
                            Celular = "11987654334",
                            DataNascimento = new DateTime(1995, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Lapa, 670",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "patricia.jpg",
                            FuncionarioId = 14,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 15,
                            CPF = "50231231245",
                            Celular = "11987654335",
                            DataNascimento = new DateTime(1988, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Av. Faria Lima, 2100",
                            Escolaridade = 4,
                            EstadoCivil = 1,
                            Foto = "eduardo.jpg",
                            FuncionarioId = 15,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 16,
                            CPF = "50231231246",
                            Celular = "11987654336",
                            DataNascimento = new DateTime(1999, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Carrão, 230",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "lucas.jpg",
                            FuncionarioId = 16,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 17,
                            CPF = "50231231247",
                            Celular = "11987654337",
                            DataNascimento = new DateTime(1998, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Butanta, 580",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "isabela.jpg",
                            FuncionarioId = 17,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 18,
                            CPF = "50231231248",
                            Celular = "11987654338",
                            DataNascimento = new DateTime(1996, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Pinheiros, 760",
                            Escolaridade = 4,
                            EstadoCivil = 1,
                            Foto = "bruno.jpg",
                            FuncionarioId = 18,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        },
                        new
                        {
                            FuncionarioDetalheId = 19,
                            CPF = "50231231249",
                            Celular = "11987654339",
                            DataNascimento = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Santana, 820",
                            Escolaridade = 3,
                            EstadoCivil = 0,
                            Foto = "larissa.jpg",
                            FuncionarioId = 19,
                            Genero = 1,
                            Nacionalidade = "Brasileira"
                        },
                        new
                        {
                            FuncionarioDetalheId = 20,
                            CPF = "50231231250",
                            Celular = "11987654340",
                            DataNascimento = new DateTime(1994, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnderecoResidencial = "Rua Moema, 450",
                            Escolaridade = 3,
                            EstadoCivil = 1,
                            Foto = "gustavo.jpg",
                            FuncionarioId = 20,
                            Genero = 0,
                            Nacionalidade = "Brasileiro"
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.FuncionariosProjetos", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("HorasTrabalhadas")
                        .HasColumnType("int");

                    b.HasKey("FuncionarioId", "ProjetoId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("FuncionariosProjetos");

                    b.HasData(
                        new
                        {
                            FuncionarioId = 1,
                            ProjetoId = 1,
                            HorasTrabalhadas = 80
                        },
                        new
                        {
                            FuncionarioId = 2,
                            ProjetoId = 1,
                            HorasTrabalhadas = 60
                        },
                        new
                        {
                            FuncionarioId = 3,
                            ProjetoId = 2,
                            HorasTrabalhadas = 90
                        },
                        new
                        {
                            FuncionarioId = 4,
                            ProjetoId = 2,
                            HorasTrabalhadas = 70
                        },
                        new
                        {
                            FuncionarioId = 5,
                            ProjetoId = 3,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 6,
                            ProjetoId = 4,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 7,
                            ProjetoId = 5,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 8,
                            ProjetoId = 6,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 9,
                            ProjetoId = 7,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 10,
                            ProjetoId = 8,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 11,
                            ProjetoId = 9,
                            HorasTrabalhadas = 40
                        },
                        new
                        {
                            FuncionarioId = 12,
                            ProjetoId = 10,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 13,
                            ProjetoId = 11,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 14,
                            ProjetoId = 12,
                            HorasTrabalhadas = 70
                        },
                        new
                        {
                            FuncionarioId = 15,
                            ProjetoId = 13,
                            HorasTrabalhadas = 35
                        },
                        new
                        {
                            FuncionarioId = 16,
                            ProjetoId = 14,
                            HorasTrabalhadas = 80
                        },
                        new
                        {
                            FuncionarioId = 17,
                            ProjetoId = 15,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 18,
                            ProjetoId = 16,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 19,
                            ProjetoId = 17,
                            HorasTrabalhadas = 50
                        },
                        new
                        {
                            FuncionarioId = 20,
                            ProjetoId = 18,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 1,
                            ProjetoId = 19,
                            HorasTrabalhadas = 100
                        },
                        new
                        {
                            FuncionarioId = 3,
                            ProjetoId = 20,
                            HorasTrabalhadas = 55
                        },
                        new
                        {
                            FuncionarioId = 5,
                            ProjetoId = 4,
                            HorasTrabalhadas = 30
                        },
                        new
                        {
                            FuncionarioId = 8,
                            ProjetoId = 10,
                            HorasTrabalhadas = 25
                        },
                        new
                        {
                            FuncionarioId = 12,
                            ProjetoId = 19,
                            HorasTrabalhadas = 35
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Projeto", b =>
                {
                    b.Property<int>("ProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjetoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInico")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Orcamento")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjetoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Projetos");

                    b.HasData(
                        new
                        {
                            ProjetoId = 1,
                            ClienteId = 1,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema de vendas",
                            Nome = "Sistema Gulosos",
                            Orcamento = 15000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 2,
                            ClienteId = 2,
                            DataAtualizacao = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Portal corporativo",
                            Nome = "Portal TechNova",
                            Orcamento = 28000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 3,
                            ClienteId = 3,
                            DataAtualizacao = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema de estoque",
                            Nome = "Sistema Mercado",
                            Orcamento = 22000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 4,
                            ClienteId = 4,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aplicativo hospitalar",
                            Nome = "App Hospital Vida",
                            Orcamento = 35000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 5,
                            ClienteId = 5,
                            DataAtualizacao = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Controle de entregas",
                            Nome = "Sistema de Entregas",
                            Orcamento = 18000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 6,
                            ClienteId = 6,
                            DataAtualizacao = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Portal acadêmico",
                            Nome = "Portal Escola Futuro",
                            Orcamento = 25000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 7,
                            ClienteId = 7,
                            DataAtualizacao = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aplicativo de pedidos",
                            Nome = "App Restaurante",
                            Orcamento = 12000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 8,
                            ClienteId = 8,
                            DataAtualizacao = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema de obras",
                            Nome = "Gestao de Obras",
                            Orcamento = 32000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 9,
                            ClienteId = 9,
                            DataAtualizacao = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aplicativo fitness",
                            Nome = "App Academia",
                            Orcamento = 14000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 10,
                            ClienteId = 10,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema bancário",
                            Nome = "Internet Banking",
                            Orcamento = 50000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 11,
                            ClienteId = 11,
                            DataAtualizacao = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema de consultas",
                            Nome = "Agenda Clinica",
                            Orcamento = 16000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 12,
                            ClienteId = 12,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Loja virtual",
                            Nome = "E-commerce Livraria",
                            Orcamento = 27000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 13,
                            ClienteId = 13,
                            DataAtualizacao = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema pet shop",
                            Nome = "Pet Feliz Online",
                            Orcamento = 13000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 14,
                            ClienteId = 14,
                            DataAtualizacao = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Agendamento oficina",
                            Nome = "Auto Center App",
                            Orcamento = 19000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 15,
                            ClienteId = 15,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema hoteleiro",
                            Nome = "Hotel Central",
                            Orcamento = 24000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 16,
                            ClienteId = 16,
                            DataAtualizacao = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "E-commerce farmacia",
                            Nome = "Farmacia Online",
                            Orcamento = 21000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 17,
                            ClienteId = 17,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema comercial",
                            Nome = "Comercial Andrade",
                            Orcamento = 17000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 18,
                            ClienteId = 18,
                            DataAtualizacao = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Portal educacional",
                            Nome = "Portal Alpha",
                            Orcamento = 30000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 19,
                            ClienteId = 19,
                            DataAtualizacao = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "ERP industrial",
                            Nome = "Metal Forte ERP",
                            Orcamento = 45000.00m,
                            Status = 10
                        },
                        new
                        {
                            ProjetoId = 20,
                            ClienteId = 20,
                            DataAtualizacao = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInico = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sistema logístico",
                            Nome = "Logistica Express",
                            Orcamento = 26000.00m,
                            Status = 10
                        });
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("JcmSoft.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.HasOne("JcmSoft.Domain.Entities.Funcionario", "Funcionario")
                        .WithOne("FuncionarioDetalhe")
                        .HasForeignKey("JcmSoft.Domain.Entities.FuncionarioDetalhe", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.FuncionariosProjetos", b =>
                {
                    b.HasOne("JcmSoft.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("FuncionarioProjetos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JcmSoft.Domain.Entities.Projeto", "Projeto")
                        .WithMany("FuncionarioProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("JcmSoft.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Projetos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("FuncionarioDetalhe");

                    b.Navigation("FuncionarioProjetos");
                });

            modelBuilder.Entity("JcmSoft.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("FuncionarioProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
